### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by jaredhirsch** [Noitidart/ostypes#8]
I'd like to use this code in [min vid](https://github.com/meandavejustice/min-vid), one of the active test pilot experiments.

You seem to use MPL 2.0 quite often, so I'm guessing that is the license for this repo, but wanted to make sure :-)

**Comment by Noitidart** [comment]
Thank you @6a68! That would be very cool! I have no idea about licensing so I just go with the default when I upload an addon haha!

Is adding a license just putting a block comment at the top?

#### Unrelated discussion - setting on top methods

If you need some ideas on how to set a window on top I can discuss that with you. You can find a stripped down version of ostypes (non-submodule) method here - https://github.com/CodeFusion/StayOnTop/blob/master/index.js#L323 - it's important to note the mac method (NSWindow) must run on the main thread. The GTK method should run on the mainthread but it will work from a worker - you may get an unexplained crash though. The GTK method is best because you can use that very easily with the native window handles obtained via XPCOM `nsIBaseWindow`. However you can do this off the main thread, you can conver the GdkWindow\* to a XWindow and use XCB (I did this somewhere but can't find it, if you need help with that I can dig it up - the method of converting GdkWindow\* to XWindow is already in ostypes submodule)

**Comment by Noitidart** [comment]
Oh shoot I just checked your code on *nix/gtk. It is using XCB but is using direct value returned from `_getNativeHandlePtrStr`, this won't work unless you first to ostypes.HELPER.gdkWinPtrToXID(_getNativeHandlePtrStr(domWin))`.

If you want to use it more directly (still have to convert GDKWindow\* to GTKWindow*) you can use `gtk_window_set_keep_above` - https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-keep-above

```
var gtkwinptr = ostypes.HELPER.gdkWinPtrToGtkWinPtr(ostypes.TYPE.GDKWindow.ptr(ctypes.UInt64(_getNativeHandlePtrStr(domWin))));
ostypes.API('gtk_window_set_keep_above')(gtkwinptr, true);
```

I simplified it a lot for the "Stay on Top" dev - https://github.com/CodeFusion/StayOnTop/blob/master/index.js#L362 - this is all in single file (no dependency on submodule) - bare bones - just took from ostypes what was needed. This bare bones implementation also shows more clearly that it depends on the version of GTK+ toolkit and how I detected it - `var TOOLKIT = Services.appinfo.widgetToolkit.toLowerCase(); var GTK_VERSION = TOOLKIT == 'gtk2' ? 2 : 3;` it seems you import this onto the main thread so have access to Servics.jsm - so getting the GTK version is automatically done by ostypes here - https://github.com/Noitidart/ostypes/blob/master/ostypes_x11.jsm#L13

**Comment by Noitidart** [comment]
You can ignore the comments here about setting on top, I made inline comments on your code :)

**Comment by jaredhirsch** [comment]
@Noitidart Whoa, thanks for the code review! I'm really excited to run through your comments tomorrow ^_^

As far as your licensing questions, the [MPL FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ) has good answers. TL;DR: You're supposed to put an MPL header in each file, because the MPL is a copyleft license at the file level--but I'm lazy, so I generally just mention the license in the readme and call it a day ;-)

**Comment by Noitidart** [comment]
Haha thank you sir for using it and giving me an opportunity to review it!

Haha love it, I'll stick it into the readme right now! :)
